site_name: Interoperability Framework
repo_url: https://github.com/Digital-Business-Council/Interoperability-Framework
pages:
    - 'Audience': 'index.md'
    - 'Disclaimer': 'disclaimer.md'
    - 'Introduction': 'introduction.md'
    - 'Motivation': 'motivation.md'
    - 'The einvoicing Interoperability Framework': 'einvoicinginteroperabilityframework.md'
    - 'Technical Specifications': 'technicalspecifications.md'
    - 'Implementation Guidance': 'implementationguidance.md'
    - 'Governance': 'governance.md'
    - 'Forward Plan': 'forwardpland.md'
    - 'References': 'references.md'
    - 'Glossary': 'glossary.md'
    - 'Appendix': 'appendix.md'
theme: mkdocs
